version: "3"
services:
  postgres.db:
    image: postgres:10.3-alpine
    volumes:
      - ./server/tmp/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  api:
    build: ./server
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    volumes:
      - ./server:/app
    ports:
      - 3001:3001
    depends_on:
      - postgres.db
    env_file:
      - ./server/.env
  web:
    build: ./client
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/usr/app/src
      - ./client/public:/usr/app/public
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./client/.env
    depends_on:
      # needed to be able to easily proxy client (package.json) to api
      # could also use docker network if depends_on gets annoying
      - api
