Location.create([{ name: 'Charlotte' }, { name: 'Denver' }, { name: 'Remote'}])

Event.create({ name: "test_event_1", category: "Conference Attendee"})
Event.create({ name: "test_event_2", category: "Conference Presenter"})
Event.create({ name: "test_event_3", category: "Online Course"})
Event.create({ name: "test_event_4", category: "In Person Course"})
Event.create({ name: "test_event_5", category: "Book"})
Event.create({ name: "test_event_6", category: "Tutorial"})
Event.create({ name: "test_event_7", category: "Other"})
Event.create({ name: "test_event_7", category: "Meetup/Social"})

Employee.create({ username: "chris", password: "12345", email: "chris@fakestartup.com", name: "Chris Brown", title: "Manager, Denver Devs", bio: "Find me cycling around Denver, writing code at @FakeStartUp, and hanging out with nerds at @Denver-Devs. Formerly of the @ctcidealab hacker space.", location_id: 2, manager_id: nil})
Employee.create({ username: "faruq", password: "12345", email: "faruq@fakestartup.com", name: "Faruq Rushdie", title: "Manager, Charlotte Devs", bio: "Faruq likes to do stuff", location_id: 1, manager_id: nil})
Employee.create({ username: "sarah", password: "12345", email: "sarah@fakestartup.com", name: "Sarah  Abramov", title: "Manager, Remote Devs", bio: "Sarah may or may not exist in real life", location_id: 3, manager_id: nil})
Employee.create({ username: "andre", password: "12345", email: "andre@fakestartup.com", name: "Andre Pohl", title: "Developer", bio: "Andre is tall and smart and nice", location_id: 2, manager_id:  1})
Employee.create({ username: "jakob", password: "12345", email: "jakob@fakestartup.com", name: "Jakob Gentes", title: "Aspiring Developer", bio: "software engineering student at @flatiron-school. formerly of the @ctcidealab. also: sound maker. picture taker. yoga teacher. writing instructor. librarian.", location_id: 2, manager_id:  1})
Employee.create({ username: "melanie", password: "12345", email: "dev@fakestartup.com", name: "Melanie Pham", title: "Developer", bio: "Melanie works remotely", location_id: 3, manager_id:  3})
Employee.create({ username: "Fatima", password: "12345", email: "fatima@fakestartup.com", name: "Fatima Ruiz", title: "Developer", bio: "Fatima rides her bike around Charlotte", location_id: 3, manager_id:  2})

Event.create({ name: "Denver Startup Week", date: "3/1/2019", category: "Conference Attendee", description: "Startup crawl", shared: 0, employee_ids: [4] })
Event.create({ name: "Lynda ES6 Course", date: "4/4/2019", category: "Online Course", description: "Functional programming basics", shared: 1, employee_ids: [5] })
Event.create({ name: "Pragmatic Programmer", date: "5/5/2019", category: "Book", description: "A riveting read", shared: 1, employee_ids: [6] })
Event.create({ name: "HackerCon", date: "6/7/2019", category: "Conference Presenter", description: "I presented on hacking", shared: 1, employee_ids: [7] })
Event.create({ name: "Graph QL 101", date: "7/8/2019", category: "In Person Course", description: "Course at General Assembly", shared: 0, employee_ids: [4] })
Event.create({ name: "What the Heck is Collection Select?", date: "8/6/2019", category: "Tutorial", description: "Online tutorial", shared: 0, employee_ids: [5] })
Event.create({ name: "Personal website", date: "8/23/2019", category: "Other", description: "Rebuilt my personal website with React.js", shared: 1, employee_ids: [6] })
Event.create({ name: "Denver Startup Week", date: "9/1/2019", category: "Conference Attendee", description: "Startup crawl", shared: 0, employee_ids: [1] })
Event.create({ name: "Denver Startup Week", date: "9/2/2019", category: "Conference Presenter", description: "Vue.js presentation", shared: 2, employee_ids: [1] })
Event.create({ name: "Think Like a Computer Programmer", date: "9/28/2019", category: "Book", description: "A good book", shared: 1, employee_ids: [7] })
Event.create({ name: "San Diego Startup Week", date: "9/29/2019", category: "Conference Attendee", description: "Talk on quantum computing", shared: 1, employee_ids: [4] })
Event.create({ name: "Denver Devs Pizza + Code", date: "10/5/2019", category: "Meetup/Social", description: "We ate pizza and built an app", shared: 0, employee_ids: [5] })

Comment.create({ content: "How was the pizza?", employee_id: 1, event_id: 12})
Comment.create({ content: "So, what the heck is it?", employee_id: 1, event_id: 6})
Comment.create({ content: "It's this great way to display a collection of objects in a Ruby form", employee_id: 5, event_id: 6})
Comment.create({ content: "Such a great book", employee_id: 3, event_id: 10})
